---
- name: Setup Vprofile Bastion Host
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - amazon.aws

  tasks:

    - name: Import Bastion variables
      include_vars: vars/bastion_setup

    - name: Import VPC output variables
      include_vars: vars/output_vars


    - name: Create vprofile EC2 key
      amazon.aws.ec2_key:
        name: "{{ keyName }}"
        region: "{{ region }}"
      register: key_out


    - name: Save private key
      copy:
        content: "{{ key_out.key.private_key }}"
        dest: "./bastion-key.pem"
        mode: "0600"
      when: key_out.changed


    - name: Create Security Group for Bastion Host
      amazon.aws.ec2_security_group:
        name: Bastion-host-sg
        description: Allow SSH access
        vpc_id: "{{ vpcid }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            ports:
              - 22
            cidr_ip: "{{ MYIP }}"
      register: BastionSG_out


    - name: Create Bastion Host
      amazon.aws.ec2_instance:
        name: Bastion_host
        key_name: "{{ keyName }}"
        instance_type: "{{ instanceType }}"
        image_id: "{{ bastion_ami }}"
        region: "{{ region }}"
        vpc_subnet_id: "{{ pubsub3id }}"
        security_group: "{{ BastionSG_out.group_id }}"
        network:
          assign_public_ip: true
        tags:
          Project: Vprofile
        wait: yes


    - name: Create EC2 in private subnet 1
      amazon.aws.ec2_instance:
        name: privsub1Instance
        key_name: "{{ keyName }}"
        instance_type: "{{ instanceType }}"
        image_id: "{{ bastion_ami }}"
        region: "{{ region }}"
        vpc_subnet_id: "{{ privsub1id }}"
        tags:
          Project: Vprofile
        wait: yes


    - name: Create EC2 in private subnet 3
      amazon.aws.ec2_instance:
        name: privsub3Instance
        key_name: "{{ keyName }}"
        instance_type: "{{ instanceType }}"
        image_id: "{{ bastion_ami }}"
        region: "{{ region }}"
        vpc_subnet_id: "{{ privsub3id }}"
        tags:
          Project: Vprofile
        wait: yes
